// Published measurements (Narayanan et al. 2021, arXiv:2104.04473, Tables 1-2) and the parameters fitted to them.
// Generated from nomo-planner/data/training_observations.csv and nomo_planner/calibrated/*.json.
import { CLUSTERS, MODELS } from "./hardware";
import { TrainingPack, type Plan } from "./packs";

export interface Observation { source: string; url: string; model: string; seq_len: string; global_batch_tokens: string; cluster: string;
  devices: string; tp: string; pp: string; zero: string; recompute: string; micro_batch: string; precision: string; metric: string;
  value: string; notes: string }

export const OBSERVATIONS: Observation[] = [
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-1.7b",
  "seq_len": "2048",
  "global_batch_tokens": "1048576",
  "cluster": "a100_nvlink_ib",
  "devices": "32",
  "tp": "1",
  "pp": "1",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "137",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-3.6b",
  "seq_len": "2048",
  "global_batch_tokens": "1048576",
  "cluster": "a100_nvlink_ib",
  "devices": "64",
  "tp": "2",
  "pp": "1",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "138",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-7.5b",
  "seq_len": "2048",
  "global_batch_tokens": "1048576",
  "cluster": "a100_nvlink_ib",
  "devices": "128",
  "tp": "4",
  "pp": "1",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "142",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-18.4b",
  "seq_len": "2048",
  "global_batch_tokens": "2097152",
  "cluster": "a100_nvlink_ib",
  "devices": "256",
  "tp": "8",
  "pp": "1",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "135",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-39.1b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "512",
  "tp": "8",
  "pp": "2",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "138",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-76.1b",
  "seq_len": "2048",
  "global_batch_tokens": "3670016",
  "cluster": "a100_nvlink_ib",
  "devices": "1024",
  "tp": "8",
  "pp": "4",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "140",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-145.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4718592",
  "cluster": "a100_nvlink_ib",
  "devices": "1536",
  "tp": "8",
  "pp": "8",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "148",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-310.1b",
  "seq_len": "2048",
  "global_batch_tokens": "4423680",
  "cluster": "a100_nvlink_ib",
  "devices": "1920",
  "tp": "8",
  "pp": "16",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "155",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "5160960",
  "cluster": "a100_nvlink_ib",
  "devices": "2520",
  "tp": "8",
  "pp": "35",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "163",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 1",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-1008b",
  "seq_len": "2048",
  "global_batch_tokens": "6291456",
  "cluster": "a100_nvlink_ib",
  "devices": "3072",
  "tp": "8",
  "pp": "64",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "163",
  "notes": "mixed precision on Selene (DGX A100); interleaved schedule; micro-batch not reported (1 assumed)"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "384",
  "tp": "8",
  "pp": "12",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "153",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "768",
  "tp": "8",
  "pp": "12",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "149",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "1536",
  "tp": "8",
  "pp": "12",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "141",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4587520",
  "cluster": "a100_nvlink_ib",
  "devices": "560",
  "tp": "8",
  "pp": "35",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "171",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4587520",
  "cluster": "a100_nvlink_ib",
  "devices": "1120",
  "tp": "8",
  "pp": "35",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "167",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4587520",
  "cluster": "a100_nvlink_ib",
  "devices": "2240",
  "tp": "8",
  "pp": "35",
  "zero": "0",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "159",
  "notes": "PTD-P; model-parallel size reported as 96 / 280"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "384",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "4",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "144",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "768",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "2",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "88",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-174.6b",
  "seq_len": "2048",
  "global_batch_tokens": "3145728",
  "cluster": "a100_nvlink_ib",
  "devices": "1536",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "44",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "5242880",
  "cluster": "a100_nvlink_ib",
  "devices": "640",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "4",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "138",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism; 640-GPU row uses batch 2560 as marked in the paper"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4587520",
  "cluster": "a100_nvlink_ib",
  "devices": "1120",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "2",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "98",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism"
 },
 {
  "source": "Narayanan et al. 2021 Table 2",
  "url": "https://arxiv.org/abs/2104.04473",
  "model": "megatron-gpt-529.6b",
  "seq_len": "2048",
  "global_batch_tokens": "4587520",
  "cluster": "a100_nvlink_ib",
  "devices": "2240",
  "tp": "1",
  "pp": "1",
  "zero": "3",
  "recompute": "full",
  "micro_batch": "1",
  "precision": "bf16",
  "metric": "megatron_tflops_per_gpu",
  "value": "48",
  "notes": "ZeRO-3 via DeepSpeed without model parallelism"
 }
];

export const CALIBRATED: Record<string, { params: Record<string, number>; observations: number; looMapePct: number; source: string }> = {
  a100_nvlink_ib: { params: {"zero3_overlap": 0.0, "e_matmul": 0.6400824774976149, "bubble_scale": 0.41036560876264244, "gemm_h_half": 320.5480034537571, "dp_overlap": 0.9999999999999999, "zero3_latency_us": 78.40485850566189}, observations: 22, looMapePct: 6.38,
    source: "Narayanan et al. 2021 (arXiv:2104.04473), Tables 1-2" },
};

/** Headline results of studies/calibrate_megatron.py (docs/CALIBRATION_REPORT.md). */
export const CALIBRATION_RESULTS = { heldOutPtdMape: 5.9, heldOutKendall: 0.84, heldOutSpearman: 0.94, looMape: 6.38, zero3TransferMape: 10.3, uncalibratedMape: 10.9 };

export interface CalibrationPoint { label: string; source: string; plan: Plan; measured: number; predicted: number; uncalibrated: number; strategy: string }

/** Measured step time from published per-GPU throughput with the paper's eq. (3), then predicted by the planner. */
export function calibrationPoints(): CalibrationPoint[] {
  return OBSERVATIONS.map((r) => {
    const model = MODELS[r.model]!;
    const devices = Number(r.devices), s = Number(r.seq_len), B = Math.floor(Number(r.global_batch_tokens) / s);
    const F = 96 * B * s * model.layers * model.hidden ** 2 * (1 + s / (6 * model.hidden) + model.vocab / (16 * model.layers * model.hidden));
    const measured = F / (devices * Number(r.value) * 1e12);
    const prob = { model, cluster: CLUSTERS[r.cluster]!, seqLen: s, globalBatchTokens: Number(r.global_batch_tokens), totalTokens: 1e12,
      deviceCounts: [devices], usableMemory: 0.92 };
    const plan: Plan = { devices, tp: Number(r.tp), pp: Number(r.pp), zero: Number(r.zero), recompute: r.recompute,
      micro_batch: Number(r.micro_batch), matmul_dtype: r.precision };
    const predicted = new TrainingPack(prob, CALIBRATED[r.cluster]!.params).evaluate(plan).breakdown.step_s as number;
    const uncalibrated = new TrainingPack(prob).evaluate(plan).breakdown.step_s as number;
    return { label: `${model.name}, ${devices} GPUs, TP${r.tp} PP${r.pp}${r.zero !== "0" ? " ZeRO-" + r.zero : ""}`,
      source: r.source, plan, measured, predicted, uncalibrated, strategy: r.zero === "3" ? "ZeRO-3" : "Tensor + pipeline" };
  });
}
