import { useMemo, useState } from "react";

import { physicalCostPerMTok, PUBLIC_COST_ROWS } from "../planner/costTracker";

export default function CostTracker() {
  const [gpuHourly, setGpuHourly] = useState(2);
  const [tokensPerSecond, setTokensPerSecond] = useState(100);
  const physical = useMemo(() => physicalCostPerMTok(gpuHourly, tokensPerSecond), [gpuHourly, tokensPerSecond]);
  return <div className="lab-neuro"><p className="section-kicker">Phase 5 public tracker</p><h2>What AI actually costs.</h2><p className="lab-lede">Published compute and provider token rows are shown with their source and date. Physical serving cost is not guessed: enter a measured GPU rate and throughput to compare it locally.</p><div className="lab-card"><div className="lab-card-head"><h3>Your physical-serving inputs</h3><span className="lab-rel warn">User input</span></div><div className="lab-fields"><label>GPU cost / hour<input type="number" min="0.01" step="0.01" value={gpuHourly} onChange={(event) => setGpuHourly(Number(event.target.value))} /></label><label>Measured output tokens / second<input type="number" min="0.01" step="0.01" value={tokensPerSecond} onChange={(event) => setTokensPerSecond(Number(event.target.value))} /></label></div><p className="lab-note">Your physical estimate: ${physical.toFixed(2)} / 1M output tokens. This value stays in the browser.</p></div><div className="lab-card"><div className="lab-prov"><table><thead><tr><th>Publisher</th><th>Item</th><th>Published value</th><th>Source / date</th></tr></thead><tbody>{PUBLIC_COST_ROWS.map((row) => <tr key={row.item}><td>{row.providerOrLab}</td><td>{row.item}</td><td>{row.kind === "provider" ? `$${row.inputUsdPerMTok!.toFixed(2)} in / $${row.outputUsdPerMTok!.toFixed(2)} out per 1M` : `${row.publishedLowUsd!.toLocaleString("en-US")} ${row.unit}`}</td><td><a href={row.sourceUrl} target="_blank" rel="noreferrer">{row.sourceTitle}</a><br /><small>{row.asOf}</small></td></tr>)}</tbody></table></div><p className="lab-note">Rows are hand-entered from publisher/model-card sources; they are not scraped at runtime. Provider prices can change and must be rechecked before procurement. Model-card GPU-hours are not dollar costs.</p></div></div>;
}
