"""Small, synthesizable RTL/EDA artifacts for an exported integer design."""
from __future__ import annotations

from typing import Any, Dict, Iterable, Optional


def _sv_int(value: int) -> str:
    return str(int(value))


def emit_pe_array(in_size: int, out_size: int, weights: Optional[Iterable[int]] = None,
                 bias: Optional[Iterable[int]] = None) -> str:
    w = list(weights or [0] * (in_size * out_size))
    b = list(bias or [0] * out_size)
    w_literal = ", ".join(_sv_int(x) for x in w)
    b_literal = ", ".join(_sv_int(x) for x in b)
    return f'''// Generated by Nomo. Integer MAC array; no floating-point arithmetic.
module pe_array #(
  parameter integer IN_SIZE = {int(in_size)},
  parameter integer OUT_SIZE = {int(out_size)}
) (
  input  logic clk,
  input  logic rst_n,
  input  logic valid_i,
  input  logic signed [7:0] x [0:IN_SIZE-1],
  output logic valid_o,
  output logic signed [31:0] y [0:OUT_SIZE-1]
);
  localparam logic signed [7:0] W [0:OUT_SIZE*IN_SIZE-1] = '{{{w_literal}}};
  localparam logic signed [31:0] B [0:OUT_SIZE-1] = '{{{b_literal}}};
  integer o, i;
  logic signed [63:0] acc;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      valid_o <= 1'b0;
      for (o = 0; o < OUT_SIZE; o = o + 1) y[o] <= '0;
    end else begin
      valid_o <= valid_i;
      if (valid_i) begin
        for (o = 0; o < OUT_SIZE; o = o + 1) begin
          acc = B[o];
          for (i = 0; i < IN_SIZE; i = i + 1) acc = acc + x[i] * W[o*IN_SIZE+i];
          y[o] <= acc[31:0];
        end
      end
    end
  end
endmodule
'''


def emit_custom_core(in_size: int, out_size: int) -> str:
    return f'''// Generated by Nomo. Top-level integer accelerator wrapper.
module custom_npu_core #(
  parameter integer IN_SIZE = {int(in_size)},
  parameter integer OUT_SIZE = {int(out_size)}
) (
  input logic clk,
  input logic rst_n,
  input logic valid_i,
  input logic signed [7:0] input_data [0:IN_SIZE-1],
  output logic valid_o,
  output logic signed [31:0] output_data [0:OUT_SIZE-1]
);
  pe_array #(.IN_SIZE(IN_SIZE), .OUT_SIZE(OUT_SIZE)) u_pe_array (
    .clk(clk), .rst_n(rst_n), .valid_i(valid_i), .x(input_data),
    .valid_o(valid_o), .y(output_data)
  );
endmodule
'''


def emit_chisel(in_size: int, out_size: int) -> str:
    return f'''// Generated by Nomo; Chisel 3 representation of the integer PE boundary.
package nomo.generated
import chisel3._

class CustomNpuCore extends Module {{
  val io = IO(new Bundle {{
    val validIn = Input(Bool())
    val input = Input(Vec({int(in_size)}, SInt(8.W)))
    val validOut = Output(Bool())
    val output = Output(Vec({int(out_size)}, SInt(32.W)))
  }})
  io.validOut := io.validIn
  for (o <- 0 until {int(out_size)}) io.output(o) := 0.S
}}
'''


def emit_eda_scripts(top: str = "custom_npu_core") -> Dict[str, str]:
    return {
        "synth.tcl": f'''# Generic Yosys/OpenROAD entry point generated by Nomo.
read_verilog -sv rtl/pe_array.sv
read_verilog -sv rtl/custom_npu_core.sv
hierarchy -check -top {top}
synth -top {top}
stat -json ppa_report.json
write_verilog -noattr -noexpr synthesized.v
''',
        "floorplan.def": '''VERSION 5.8 ;
DIVIDERCHAR "/" ; BUSBITCHARS "[]" ;
DESIGN nomo_floorplan ;
UNITS DISTANCE MICRONS 1000 ;
COMPONENTS 0 ;
END COMPONENTS
NETS 0 ;
END NETS
END DESIGN
''',
    }


def proxy_ppa(model: Any, evaluation: Optional[Any] = None) -> Dict[str, Any]:
    layers = list(getattr(model, "layers", []))
    cells = int(sum(max(1, int(getattr(l, "params", 0))) for l in layers))
    area = float(cells * 0.42 + max(1, len(layers)) * 125.0)
    latency = float(getattr(getattr(evaluation, "cost", None), "latency_s", 0.0) or 0.0)
    energy = float(getattr(getattr(evaluation, "cost", None), "energy_j", 0.0) or 0.0)
    return {"format": "nomo.ppa/1", "source": "proxy", "verified_by": None,
            "area_um2": area, "gate_count": cells * 3 + 128, "power_mw": energy / max(latency, 1e-12) * 1e3,
            "performance_mhz": 1.0 / max(latency, 1e-12) / 1e6 if latency else None,
            "assumption": "area and power are synthesis-independent estimates; run the generated Yosys/OpenROAD scripts for measured PPA"}
