/** Plain-English definitions shown in tooltips. Keep each to two short sentences. */
export const GLOSSARY: Record<string, { title: string; body: string }> = {
  continuous: { title: "Continuous (standard) layer",
    body: "A normal neural-network layer that computes every number every time. Accurate and fast, but it always does the full amount of work." },
  spiking: { title: "Spiking layer",
    body: "A brain-style layer whose neurons only send a signal (a spike) when they have something to say. Quiet inputs cost almost nothing, which saves energy on neuromorphic chips." },
  symbolic: { title: "Physics formula / symbolic layer",
    body: "A layer replaced by an exact formula, such as the equations of how a drone rotates. Exact and cheap, but only possible where such a formula exists." },
  rate: { title: "Rate coding",
    body: "A value is sent as how often a neuron fires over a short window. Robust and accurate, but it uses more spikes." },
  ttfs: { title: "Time-to-first-spike (TTFS)",
    body: "Each neuron fires at most once, and firing earlier means a bigger value. Very few spikes, so very little energy." },
  phase: { title: "Phase coding",
    body: "Values are carried by when spikes occur relative to a background rhythm. Nomo does not model it yet, so it cannot be selected." },
  crossing: { title: "Domain crossing",
    body: "A point where data changes style, for example from numbers to spikes. Each crossing costs a little energy and time for the conversion." },
  crossing_penalty: { title: "Crossing penalty",
    body: "Makes the search prefer designs with fewer style changes. At 0.1, every crossing counts as 10% extra energy and latency when ranking designs; reported numbers stay real." },
  min_saving: { title: "Minimum saving for mixed designs",
    body: "A design that mixes styles must beat the all-continuous version by at least this much energy or latency, otherwise it is rejected." },
  pareto: { title: "Best trade-offs (Pareto front)",
    body: "Designs where you cannot improve energy, speed or accuracy without making another one worse. Every other design is beaten by one of these." },
  hypervolume: { title: "Hypervolume",
    body: "One score for how good the whole set of trade-offs is. It rises while the search improves and levels off when it has converged." },
  sram: { title: "SRAM per core",
    body: "The small, fast memory on each chip core that stores weights. If a layer's weights don't fit, it needs more cores." },
  mac_energy: { title: "Energy per multiply-add",
    body: "Energy for one multiply-and-add, the basic step of a standard layer, in picojoules (trillionths of a joule)." },
  sop_energy: { title: "Energy per synaptic event",
    body: "Energy for one spike arriving at one connection on the neuromorphic part of the chip, in picojoules." },
  routing_latency: { title: "Spike routing latency",
    body: "Fixed delay for data to hop between parts of the chip, in microseconds." },
  bus_bandwidth: { title: "Bus bandwidth",
    body: "How fast data moves between the chip's processors, in gigabytes per second." },
  clock: { title: "Clock frequency",
    body: "How fast the chip runs. Lower clocks make every step slower; with always-on power, that can raise energy per decision." },
  static_power: { title: "Always-on (static) power",
    body: "Power the chip draws just by being switched on, even when idle. Slower designs pay more of it per decision." },
  precision: { title: "Precision (bits)",
    body: "How many bits store each weight. Fewer bits means smaller and cheaper, and slightly less accurate. Binary uses one bit per weight." },
  lock: { title: "Layer lock",
    body: "Forces a layer to one style or precision. The search treats it as a hard rule and optimises everything else around it." },
  population: { title: "Population size",
    body: "How many designs the search keeps and improves at once. Bigger explores more but takes longer." },
  generations: { title: "Generations",
    body: "How many rounds of improvement the search runs. It stops early once results stop improving." },
  mutation: { title: "Mutation probability",
    body: "How often a new design gets a small random change on top of combining two parents. Higher explores more widely." },
  crossover: { title: "Crossover probability",
    body: "How often a new design is made by combining two good parents rather than copying one." },
  archive: { title: "Trade-off archive size",
    body: "The maximum number of best trade-offs to keep and show. 0 keeps them all; a smaller number keeps the most spread-out ones." },
  patience: { title: "Patience",
    body: "The search stops if results have not improved for this many rounds." },
  accuracy_drop: { title: "Allowed accuracy drop",
    body: "How many percentage points of accuracy you are willing to give up compared with your original model." },
  estimated: { title: "Estimated accuracy",
    body: "Accuracy is predicted from how sensitive each layer is to each change, not measured on your data. Check the final design on your own test set." },
  placeholder: { title: "Placeholder chip numbers",
    body: "Built-in energy and speed figures are representative estimates, not measurements. Enter your own chip data under Chip parameters for real numbers." },
  cores: { title: "Neuromorphic cores",
    body: "Neuromorphic chips are made of many small cores; each holds a limited number of neurons and weights." },
};
